export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_MAGIC_LINK_EXPIRED: 'AUTH_MAGIC_LINK_EXPIRED',
  AUTH_WS_ORIGIN_DENIED: 'AUTH_WS_ORIGIN_DENIED',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  FORBIDDEN_SCOPE: 'FORBIDDEN_SCOPE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CONFLICT_DUPLICATE: 'CONFLICT_DUPLICATE',
  CONFLICT_ACTIVE_ORDERS: 'CONFLICT_ACTIVE_ORDERS',
  CONFLICT_OPTIMISTIC_LOCK: 'CONFLICT_OPTIMISTIC_LOCK',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_INVALID_TRANSITION: 'VALIDATION_INVALID_TRANSITION',
  VALIDATION_FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',

  // Prisma
  PRISMA_UNIQUE_CONSTRAINT: 'PRISMA_UNIQUE_CONSTRAINT',
  PRISMA_FOREIGN_KEY: 'PRISMA_FOREIGN_KEY',
  PRISMA_NOT_FOUND: 'PRISMA_NOT_FOUND',
  PRISMA_REQUIRED_RELATION: 'PRISMA_REQUIRED_RELATION',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
  WS_RATE_LIMITED: 'WS_RATE_LIMITED',

  // WebSocket
  WS_AUTH_FAILED: 'WS_AUTH_FAILED',
  WS_MISSING_TOKEN: 'WS_MISSING_TOKEN',
  WS_ACCESS_DENIED: 'WS_ACCESS_DENIED',

  // External services
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  STORAGE_DELETE_FAILED: 'STORAGE_DELETE_FAILED',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
  NOTIFICATION_ADAPTER_MISSING: 'NOTIFICATION_ADAPTER_MISSING',
  REPORTING_ERROR: 'REPORTING_ERROR',
  GEOCODING_ERROR: 'GEOCODING_ERROR',

  // Internal
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
